CREATE TABLE IF NOT EXISTS reviews (
  id SERIAL PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  phone VARCHAR(50) NOT NULL,
  message TEXT,
  rating INTEGER DEFAULT 5,
  created_at TIMESTAMP DEFAULT NOW()
);